# Generated by Django 3.2.3 on 2021-05-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0005_auto_20210531_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='link',
        ),
    ]
