# Generated by Django 3.2.3 on 2021-05-31 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0006_remove_recipe_link'),
    ]

    operations = [
    #    migrations.RemoveField(
    #        model_name='saved',
    #        name='owner',
    #    ),
    ]
