# Generated by Django 3.2.3 on 2021-05-31 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0007_remove_saved_owner'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='recipe',
        #    name='full_recipe',
        #),
        #migrations.AlterField(
        #    model_name='fullrecipe',
        #    name='preview',
        #    field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipesite.recipe'),
        #),
    ]
