# Generated by Django 3.2.3 on 2021-05-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0008_auto_20210601_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullrecipe',
            name='preview',
            field=models.CharField(max_length=20, null=True, verbose_name='К кому относится'),
        ),
    ]
