# Generated by Django 3.2.3 on 2021-06-01 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0009_alter_fullrecipe_preview'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='saved',
        #    name='full_recipe',
        #),
    ]
