# Generated by Django 3.2.3 on 2021-06-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0010_remove_saved_full_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullrecipe',
            name='preview_image',
            field=models.CharField(max_length=20, null=True, verbose_name='К кому относится'),
        ),
        migrations.AlterField(
            model_name='fullrecipe',
            name='preview',
            field=models.ImageField(upload_to=''),
        ),
    ]
