# Generated by Django 3.2.3 on 2021-06-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0011_auto_20210601_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullRecipeSaved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('description1', models.TextField(verbose_name='Описание1')),
                ('description2', models.TextField(verbose_name='Описание2')),
                ('preview', models.ImageField(upload_to='')),
                ('motivation', models.ImageField(upload_to='')),
                ('preview_image', models.CharField(max_length=20, null=True, verbose_name='К кому относится')),
            ],
        ),
    ]
