# Generated by Django 3.2.3 on 2021-06-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0013_auto_20210602_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullrecipe',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='saved',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
