# Generated by Django 3.2.3 on 2021-06-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0014_auto_20210602_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullrecipe',
            name='preview_image',
            field=models.CharField(max_length=40, null=True, verbose_name='К кому относится'),
        ),
        migrations.AlterField(
            model_name='fullrecipesaved',
            name='preview_image',
            field=models.CharField(max_length=40, null=True, verbose_name='К кому относится'),
        ),
        migrations.AlterField(
            model_name='fullrecipesaved',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
