# Generated by Django 3.2.3 on 2021-06-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0017_auto_20210602_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullrecipe',
            name='ingredient1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ингредиент 1'),
        ),
        migrations.AlterField(
            model_name='fullrecipe',
            name='ingredient2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ингредиент 2'),
        ),
        migrations.AlterField(
            model_name='fullrecipe',
            name='ingredient3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ингредиент 3'),
        ),
        migrations.AlterField(
            model_name='fullrecipe',
            name='ingredient4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ингредиент 4'),
        ),
        migrations.AlterField(
            model_name='fullrecipe',
            name='ingredient5',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ингредиент 5'),
        ),
        migrations.AlterField(
            model_name='fullrecipe',
            name='ingredient6',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ингредиент 6'),
        ),
        migrations.AlterField(
            model_name='fullrecipesaved',
            name='ingredient1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ингредиент 1'),
        ),
        migrations.AlterField(
            model_name='fullrecipesaved',
            name='ingredient2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ингредиент 2'),
        ),
        migrations.AlterField(
            model_name='fullrecipesaved',
            name='ingredient3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ингредиент 3'),
        ),
        migrations.AlterField(
            model_name='fullrecipesaved',
            name='ingredient4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ингредиент 4'),
        ),
        migrations.AlterField(
            model_name='fullrecipesaved',
            name='ingredient5',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ингредиент 5'),
        ),
        migrations.AlterField(
            model_name='fullrecipesaved',
            name='ingredient6',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ингредиент 6'),
        ),
    ]
