# Generated by Django 3.2.3 on 2021-06-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipesite', '0018_auto_20210602_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='save_check',
            field=models.BooleanField(default=False),
        ),
    ]
